---
title: "1er Trabajo Práctico de Econometría"
author: "Mauro y Juan Camilo"
format: pdf
lang: es
editor: visual
---

## Librerías

```{r}
#| output: false

library(tidyverse)    #Para manejar bases de datos
library(ggplot2)      #Para graficar
library(eph)          #Librería hecha por científicos argentinos
library(tinytable)    #Para las tablas
library(modelsummary) #Mejores tablas de regresión 
```

```{r}
#| include: false

options(tinytable_tt_digits = 3)
options(tinytable_theme_placement_latex_float = "H")
```

```{r}
#| include: false

df <- get_microdata(year = 2023, trimester = 4, type = 'individual') %>% 
organize_labels(type='individual') 
```

```{r}
#| include: false

df <- df %>% mutate_at(vars(NIVEL_ED, AGLOMERADO, CH07, ESTADO, REGION), ~as.factor(.))
```

Nos quedamos únicamente con los jefes de hogar, hombres, con edades entre 25 y 65 años, ocupados y asalariados.

```{r}
#| output: false

df <- df %>% 
  filter(CH03 == 1,           #Jefes/as de hogar
         CH04 == 1,           #Hombres          
         CH06 >= 25,          #Entre 25...      
         CH06 <= 65,          #...y 65 años     
         ESTADO == "Ocupado", #Ocupados         
         CAT_OCUP == 3,       #Asalariados      
         P21 > 0,             #Salario positivo 
         CH12 < 9             #Todos los niveles educ salvo 'educ especial'
                   )
```

Generamos las variables que necesitamos, lo cual se ve en @tbl-salario:

```{r}
#| label: tbl-salario
#| tbl-cap: "Salario"
#| echo: false
#| include: false

df <- df %>% 
  mutate(logSal = log(df$P21))

tabla <- df %>% 
  select(c("P21", "logSal"))

tt(tabla)
```

En @tbl-mincer pueden leerse los resultados de la primer regresión.

```{r}
#| label: tbl-mincer
#| tbl-cap: "Ecuación de Mincer"

reg1 <- lm(logSal ~ CH06 + NIVEL_ED + CH07 + AGLOMERADO, data = df)

reg2 <- lm(logSal ~ CH06 + NIVEL_ED + CH07 + REGION, data = df)

modelsummary(list("Por Aglomerado" = reg1,"Por Región" = reg2). longtable = TRUE)
```
